spring.application.name=Shade
# Telegram Bot Configuration

telegram.logbot.token=8704286083:AAGwwjbo11w-CLYla3sktmSNky4d3WQJ9Rs
telegram.logbot.username=@XonPeyTest2Bot



telegram.bot.username=@XonPeyTestBot
telegram.bot.token=8347349335:AAEU1d_aSfvQRxbv2Mu_rl7D-loAWLiNUjM


spring.messages.fallback-to-system-locale=true
spring.messages.cache-duration=-1


telegram.admin.log.bot.username=@XonPeyTest1Bot
telegram.admin.log.bot.token=8674285177:AAEDrMBYllY2bkzwIrIxnDKyuBBDOk4mEgw


spring.datasource.url=jdbc:postgresql://localhost:5432/telegram_payment_bot
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
