spring.application.name=Shade
# Telegram Bot Configuration

telegram.logbot.token=8910943154:AAEzXkcqeVH0qrQo02vkkmmVnL0glRfD0f8
telegram.logbot.username=@lotto_wins_bot



telegram.bot.username=@Baronpeybot
telegram.bot.token=8926934764:AAGUziymNKLeqbr0voT_OLbuOlAs-Nk0wl4


spring.messages.fallback-to-system-locale=true
spring.messages.cache-duration=-1


telegram.admin.log.bot.username=@Baronpeysupportbot
telegram.admin.log.bot.token=8688828421:AAGWj7IOnTXAWa3fJe7oGTPcziAWmogZslE


spring.datasource.url=jdbc:postgresql://localhost:5432/telegram_payment_bot
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
